/** Device pairing (spec §4): exchanges a short-lived pairing code (generated by the browser,
 * shown to the user, typed into this agent — see `tray.ts`) for a permanent `device_id` + device
 * secret, calling the backend endpoints implemented in `backend/app/modules/printing/router.py`.
 * The secret is written to disk only via `secureStorage.protect()` — see config.ts's comment on
 * why it never lives in `config.json` itself. */

import { readFile, writeFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import type { AgentConfig } from './config.js';
import { AGENT_VERSION, detectPlatform, saveConfig, secretPath } from './config.js';
import { protect, unprotect } from './secureStorage.js';

export interface PairResult {
  deviceId: string;
}

interface PairApiResponse {
  data: { device_id: string; device_secret: string; tenant_id: string };
}

interface PublicKeyApiResponse {
  data: { public_key: string };
}

export class PairingError extends Error {}

/** Exchanges a pairing code for a device identity. Called from the tray "Enter Pairing Code"
 * prompt — never from an unauthenticated WS message (see server.ts's comment on why pairing must
 * go through the OS-native tray UI, not the browser-facing socket). */
export async function pairDevice(config: AgentConfig, pairingCode: string): Promise<PairResult> {
  const res = await fetch(`${config.backendUrl}/api/printing/agent/pair`, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      pairing_code: pairingCode,
      platform: detectPlatform(),
      agent_version: AGENT_VERSION,
      device_fingerprint: config.deviceFingerprint,
    }),
  });
  if (!res.ok) {
    // FastAPI's HTTPException (raised for every error case in this endpoint) serializes as
    // {"detail": "..."} — not make_response()'s {"message": ...} shape, which is only used on the
    // success path. Confirmed against the actual backend implementation.
    const body = await res.json().catch(() => null);
    throw new PairingError((body as { detail?: string } | null)?.detail ?? `Pairing failed (HTTP ${res.status}).`);
  }
  const { data } = (await res.json()) as PairApiResponse;
  await writeFile(secretPath(), await protect(data.device_secret), 'utf8');
  // Mutated in place, not copied — `config` is the single shared instance server.ts/adminHttp.ts
  // both hold a reference to for the lifetime of the process. Persisting a *copy* to disk (as an
  // earlier version of this function did) left the live in-memory object's deviceId/public key
  // stale until the next restart, so the very first WS auth attempt right after pairing would
  // fail with "no cached verification key yet" even though pairing itself had just succeeded.
  config.deviceId = data.device_id;
  config.tenantId = data.tenant_id;
  await saveConfig(config);
  // Fetch the token verification key now, not just at next startup — server.ts's auth handler
  // needs tenantTokenPublicKeyPem to verify the very first session token the browser presents,
  // which can arrive within seconds of pairing (see index.ts's own startup-time fetch, which only
  // covers an *already*-paired agent restarting, not a brand-new pairing like this one).
  await ensureTokenPublicKey(config);
  return { deviceId: data.device_id };
}

/** Fetches and locally caches the RSA public key the backend uses to sign session tokens (see
 * `tokenVerify.ts`) — cached in config.json since it changes only if the deployment rotates its
 * signing key, and caching it lets the agent verify tokens fully offline afterward (spec §13).
 * Mutates `config` in place — see `pairDevice`'s comment on why that matters here specifically. */
export async function ensureTokenPublicKey(config: AgentConfig): Promise<string> {
  if (config.tenantTokenPublicKeyPem) return config.tenantTokenPublicKeyPem;
  const res = await fetch(`${config.backendUrl}/api/printing/agent/token-public-key`);
  if (!res.ok) throw new PairingError(`Could not fetch the token verification key (HTTP ${res.status}).`);
  const { data } = (await res.json()) as PublicKeyApiResponse;
  config.tenantTokenPublicKeyPem = data.public_key;
  await saveConfig(config);
  return data.public_key;
}

export async function loadDeviceSecret(): Promise<string | null> {
  if (!existsSync(secretPath())) return null;
  const blob = await readFile(secretPath(), 'utf8');
  return unprotect(blob);
}
