"""baseline: current admin schema

Revision ID: 98d0de5b3882
Revises: 
Create Date: 2026-07-30 17:13:22.229674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98d0de5b3882'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_communications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_name', sa.String(length=200), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=4000), nullable=False),
    sa.Column('audience_type', sa.String(length=20), nullable=False),
    sa.Column('audience_filter', sa.JSON(), nullable=True),
    sa.Column('recipient_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_communications_admin_user_id'), 'admin_communications', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_communications_created_at'), 'admin_communications', ['created_at'], unique=False)
    op.create_table('admin_notifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('dedup_key', sa.String(length=150), nullable=False),
    sa.Column('type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notifications_created_at'), 'admin_notifications', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_notifications_dedup_key'), 'admin_notifications', ['dedup_key'], unique=True)
    op.create_index(op.f('ix_admin_notifications_tenant_id'), 'admin_notifications', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_admin_notifications_type'), 'admin_notifications', ['type'], unique=False)
    op.create_table('admin_users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_invalidated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('must_change_password', sa.Boolean(), nullable=False),
    sa.Column('invited_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_users_email'), 'admin_users', ['email'], unique=True)
    op.create_table('feature_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('modules', sa.JSON(), nullable=False),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_by_admin_id', sa.String(length=36), nullable=True),
    sa.Column('created_by_admin_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('admin_audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_name', sa.String(length=200), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('target_type', sa.String(length=50), nullable=True),
    sa.Column('target_id', sa.String(length=36), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_audit_log_action'), 'admin_audit_log', ['action'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_admin_user_id'), 'admin_audit_log', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_created_at'), 'admin_audit_log', ['created_at'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_target_id'), 'admin_audit_log', ['target_id'], unique=False)
    op.create_table('admin_invite_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invite_tokens_admin_user_id'), 'admin_invite_tokens', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_invite_tokens_token_hash'), 'admin_invite_tokens', ['token_hash'], unique=True)
    op.create_table('admin_notification_reads',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('notification_id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.ForeignKeyConstraint(['notification_id'], ['admin_notifications.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_notification_reads_admin_user_id'), 'admin_notification_reads', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_notification_reads_notification_id'), 'admin_notification_reads', ['notification_id'], unique=False)
    op.create_table('admin_refresh_tokens',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('admin_user_id', sa.String(length=36), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['admin_users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_refresh_tokens_admin_user_id'), 'admin_refresh_tokens', ['admin_user_id'], unique=False)
    op.create_index(op.f('ix_admin_refresh_tokens_token_hash'), 'admin_refresh_tokens', ['token_hash'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admin_refresh_tokens_token_hash'), table_name='admin_refresh_tokens')
    op.drop_index(op.f('ix_admin_refresh_tokens_admin_user_id'), table_name='admin_refresh_tokens')
    op.drop_table('admin_refresh_tokens')
    op.drop_index(op.f('ix_admin_notification_reads_notification_id'), table_name='admin_notification_reads')
    op.drop_index(op.f('ix_admin_notification_reads_admin_user_id'), table_name='admin_notification_reads')
    op.drop_table('admin_notification_reads')
    op.drop_index(op.f('ix_admin_invite_tokens_token_hash'), table_name='admin_invite_tokens')
    op.drop_index(op.f('ix_admin_invite_tokens_admin_user_id'), table_name='admin_invite_tokens')
    op.drop_table('admin_invite_tokens')
    op.drop_index(op.f('ix_admin_audit_log_target_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_created_at'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_admin_user_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_admin_audit_log_action'), table_name='admin_audit_log')
    op.drop_table('admin_audit_log')
    op.drop_table('feature_templates')
    op.drop_index(op.f('ix_admin_users_email'), table_name='admin_users')
    op.drop_table('admin_users')
    op.drop_index(op.f('ix_admin_notifications_type'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_tenant_id'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_dedup_key'), table_name='admin_notifications')
    op.drop_index(op.f('ix_admin_notifications_created_at'), table_name='admin_notifications')
    op.drop_table('admin_notifications')
    op.drop_index(op.f('ix_admin_communications_created_at'), table_name='admin_communications')
    op.drop_index(op.f('ix_admin_communications_admin_user_id'), table_name='admin_communications')
    op.drop_table('admin_communications')
    # ### end Alembic commands ###
