"""add price override audit and settings toggle

Revision ID: 02fa97fef862
Revises: 7c6d93fc3c50
Create Date: 2026-07-22 11:51:14.364920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02fa97fef862'
down_revision: Union[str, Sequence[str], None] = '7c6d93fc3c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('price_override_audits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('original_price', sa.Float(), nullable=False),
    sa.Column('new_price', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_override_audits_invoice_id'), 'price_override_audits', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_price_override_audits_tenant_id'), 'price_override_audits', ['tenant_id'], unique=False)
    # Note: no create_foreign_key for products.category_id here — SQLite cannot
    # ALTER-add an FK constraint without a full table rebuild (batch mode), and
    # FK enforcement isn't enabled anywhere in this app; see the equivalent note
    # in 45ee19d853cb_add_categories_customers_settings_split_.py.
    op.add_column('settings', sa.Column('allow_manager_price_override', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'allow_manager_price_override')
    op.drop_index(op.f('ix_price_override_audits_tenant_id'), table_name='price_override_audits')
    op.drop_index(op.f('ix_price_override_audits_invoice_id'), table_name='price_override_audits')
    op.drop_table('price_override_audits')
    # ### end Alembic commands ###
