"""add tenant phone_type

Revision ID: 3efbbd3b5795
Revises: 7a14e0452f66
Create Date: 2026-07-21 13:27:05.663220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3efbbd3b5795'
down_revision: Union[str, Sequence[str], None] = '7a14e0452f66'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'tenants', sa.Column('phone_type', sa.String(length=20), nullable=False, server_default='mobile')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'phone_type')
    # ### end Alembic commands ###
