"""add categories customers settings, split tenant settings

Revision ID: 45ee19d853cb
Revises: 3efbbd3b5795
Create Date: 2026-07-21 14:51:22.348042

"""
from datetime import datetime, timezone
from typing import Sequence, Union
from uuid import uuid4

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ee19d853cb'
down_revision: Union[str, Sequence[str], None] = '3efbbd3b5795'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_tenant_id'), 'categories', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_mobile'), 'customers', ['mobile'], unique=False)
    op.create_index(op.f('ix_customers_name'), 'customers', ['name'], unique=False)
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('gst_number', sa.String(length=30), nullable=True),
    sa.Column('invoice_prefix', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('theme', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_settings_tenant_id'), 'settings', ['tenant_id'], unique=True)

    # Backfill one Settings row per existing tenant, copying its current
    # logo_url/currency/theme values before those columns are dropped below.
    bind = op.get_bind()
    tenants_table = sa.table(
        'tenants',
        sa.column('id', sa.String),
        sa.column('logo_url', sa.String),
        sa.column('currency', sa.String),
        sa.column('theme', sa.String),
    )
    settings_table = sa.table(
        'settings',
        sa.column('id', sa.String),
        sa.column('tenant_id', sa.String),
        sa.column('logo_url', sa.String),
        sa.column('gst_number', sa.String),
        sa.column('invoice_prefix', sa.String),
        sa.column('currency', sa.String),
        sa.column('theme', sa.String),
        sa.column('created_at', sa.DateTime),
        sa.column('updated_at', sa.DateTime),
    )
    existing_tenants = bind.execute(sa.select(tenants_table.c.id, tenants_table.c.logo_url, tenants_table.c.currency, tenants_table.c.theme)).fetchall()
    now = datetime.now(timezone.utc)
    for tenant_id, logo_url, currency, theme in existing_tenants:
        bind.execute(
            settings_table.insert().values(
                id=str(uuid4()),
                tenant_id=tenant_id,
                logo_url=logo_url,
                gst_number=None,
                invoice_prefix="INV",
                currency=currency or "INR",
                theme=theme or "light",
                created_at=now,
                updated_at=now,
            )
        )

    op.add_column('products', sa.Column('category_id', sa.String(length=36), nullable=True))
    op.drop_index(op.f('ix_products_category'), table_name='products')
    op.create_index(op.f('ix_products_category_id'), 'products', ['category_id'], unique=False)
    # Note: SQLite cannot ALTER a table to add an FK constraint without a full
    # table rebuild (batch mode); FK enforcement isn't enabled anywhere in this
    # app (no PRAGMA foreign_keys=ON in app/core/db.py), so the ORM-level
    # ForeignKey on Product.category_id governs joins/queries without a DB-level
    # constraint, consistent with every other FK column in this schema.
    op.drop_column('products', 'category')
    op.drop_column('tenants', 'theme')
    op.drop_column('tenants', 'currency')
    op.drop_column('tenants', 'logo_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('logo_url', sa.VARCHAR(length=500), nullable=True))
    op.add_column('tenants', sa.Column('currency', sa.VARCHAR(length=3), nullable=False))
    op.add_column('tenants', sa.Column('theme', sa.VARCHAR(length=16), nullable=False))
    op.add_column('products', sa.Column('category', sa.VARCHAR(length=150), nullable=True))
    op.drop_index(op.f('ix_products_category_id'), table_name='products')
    op.create_index(op.f('ix_products_category'), 'products', ['category'], unique=False)
    op.drop_column('products', 'category_id')
    op.drop_index(op.f('ix_settings_tenant_id'), table_name='settings')
    op.drop_table('settings')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_name'), table_name='customers')
    op.drop_index(op.f('ix_customers_mobile'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_categories_tenant_id'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
