"""add returns and payment status

Revision ID: 4ed26af3ad72
Revises: b2f2b08c9c54
Create Date: 2026-07-23 09:41:34.472339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ed26af3ad72'
down_revision: Union[str, Sequence[str], None] = 'b2f2b08c9c54'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('returns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_id', sa.String(length=36), nullable=False),
    sa.Column('return_number', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('refund_amount', sa.Float(), nullable=False),
    sa.Column('refund_method', sa.String(length=10), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['invoice_id'], ['invoices.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_returns_created_at'), 'returns', ['created_at'], unique=False)
    op.create_index(op.f('ix_returns_invoice_id'), 'returns', ['invoice_id'], unique=False)
    op.create_index(op.f('ix_returns_return_number'), 'returns', ['return_number'], unique=False)
    op.create_index(op.f('ix_returns_tenant_id'), 'returns', ['tenant_id'], unique=False)
    op.create_table('return_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('return_id', sa.String(length=36), nullable=False),
    sa.Column('invoice_item_id', sa.String(length=36), nullable=False),
    sa.Column('product_id', sa.String(length=36), nullable=False),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('quantity_returned', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('line_refund_amount', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_item_id'], ['invoice_items.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['return_id'], ['returns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_return_items_return_id'), 'return_items', ['return_id'], unique=False)
    op.add_column(
        'invoice_items',
        sa.Column('returned_quantity', sa.Float(), nullable=False, server_default='0'),
    )
    # ### end Alembic commands ###

    # Backfill: "void" is renamed to "cancelled" now that Invoice.status carries the wider
    # paid/partial/cancelled/refunded set (Phase 1 — Payment Status).
    op.execute("UPDATE invoices SET status = 'cancelled' WHERE status = 'void'")


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("UPDATE invoices SET status = 'void' WHERE status = 'cancelled'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoice_items', 'returned_quantity')
    op.drop_index(op.f('ix_return_items_return_id'), table_name='return_items')
    op.drop_table('return_items')
    op.drop_index(op.f('ix_returns_tenant_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_return_number'), table_name='returns')
    op.drop_index(op.f('ix_returns_invoice_id'), table_name='returns')
    op.drop_index(op.f('ix_returns_created_at'), table_name='returns')
    op.drop_table('returns')
    # ### end Alembic commands ###
