"""add settings.plan and invoices.gst_number

Revision ID: 7c6d93fc3c50
Revises: 45ee19d853cb
Create Date: 2026-07-21 18:45:39.002400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c6d93fc3c50'
down_revision: Union[str, Sequence[str], None] = '45ee19d853cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('gst_number', sa.String(length=30), nullable=True))
    # Note: no create_foreign_key for products.category_id here — SQLite cannot
    # ALTER-add an FK constraint without a full table rebuild (batch mode), and
    # FK enforcement isn't enabled anywhere in this app; see the equivalent note
    # in 45ee19d853cb_add_categories_customers_settings_split_.py.
    op.add_column('settings', sa.Column('plan', sa.String(length=20), nullable=False, server_default='basic'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'plan')
    op.drop_column('invoices', 'gst_number')
    # ### end Alembic commands ###
