"""add product and customer import tables

Revision ID: a4358eccb52c
Revises: 7451c30ec351
Create Date: 2026-07-23 15:33:48.164049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4358eccb52c'
down_revision: Union[str, Sequence[str], None] = '7451c30ec351'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_import_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_import_history_tenant_id'), 'customer_import_history', ['tenant_id'], unique=False)
    op.create_table('product_import_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=False),
    sa.Column('column_mapping', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('rows_total', sa.Integer(), nullable=False),
    sa.Column('rows_imported', sa.Integer(), nullable=False),
    sa.Column('rows_failed', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_import_history_tenant_id'), 'product_import_history', ['tenant_id'], unique=False)
    op.create_table('customer_import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('matched_customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('mobile', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['import_id'], ['customer_import_history.id'], ),
    sa.ForeignKeyConstraint(['matched_customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_import_rows_import_id'), 'customer_import_rows', ['import_id'], unique=False)
    op.create_index(op.f('ix_customer_import_rows_tenant_id'), 'customer_import_rows', ['tenant_id'], unique=False)
    op.create_table('product_import_rows',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('import_id', sa.String(length=36), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('raw_data', sa.JSON(), nullable=False),
    sa.Column('matched_product_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('identifier_value', sa.String(length=80), nullable=True),
    sa.Column('category_id', sa.String(length=36), nullable=True),
    sa.Column('cost_price', sa.Float(), nullable=True),
    sa.Column('selling_price', sa.Float(), nullable=True),
    sa.Column('tax_rate_percent', sa.Float(), nullable=True),
    sa.Column('barcode', sa.String(length=80), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error_messages', sa.JSON(), nullable=True),
    sa.Column('is_skipped', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['import_id'], ['product_import_history.id'], ),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_import_rows_import_id'), 'product_import_rows', ['import_id'], unique=False)
    op.create_index(op.f('ix_product_import_rows_tenant_id'), 'product_import_rows', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_product_import_rows_tenant_id'), table_name='product_import_rows')
    op.drop_index(op.f('ix_product_import_rows_import_id'), table_name='product_import_rows')
    op.drop_table('product_import_rows')
    op.drop_index(op.f('ix_customer_import_rows_tenant_id'), table_name='customer_import_rows')
    op.drop_index(op.f('ix_customer_import_rows_import_id'), table_name='customer_import_rows')
    op.drop_table('customer_import_rows')
    op.drop_index(op.f('ix_product_import_history_tenant_id'), table_name='product_import_history')
    op.drop_table('product_import_history')
    op.drop_index(op.f('ix_customer_import_history_tenant_id'), table_name='customer_import_history')
    op.drop_table('customer_import_history')
    # ### end Alembic commands ###
