"""add business preferences and invoice settings

Revision ID: bebaaf6bef98
Revises: e9782d44c912
Create Date: 2026-07-23 11:15:23.865394

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bebaaf6bef98'
down_revision: Union[str, Sequence[str], None] = 'e9782d44c912'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('starting_invoice_number', sa.Integer(), nullable=False, server_default='1'))
    op.add_column('settings', sa.Column('receipt_footer', sa.Text(), nullable=True))
    op.add_column('settings', sa.Column('decimal_precision', sa.Integer(), nullable=False, server_default='2'))
    op.add_column('settings', sa.Column('date_format', sa.String(length=20), nullable=False, server_default='DD/MM/YYYY'))
    op.add_column('settings', sa.Column('default_tax_percent', sa.Float(), nullable=False, server_default='0'))
    op.add_column('settings', sa.Column('allow_discounts', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('settings', sa.Column('auto_print_after_checkout', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('settings', sa.Column('enable_barcode', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('settings', sa.Column('enable_customer_selection', sa.Boolean(), nullable=False, server_default=sa.false()))
    op.add_column('settings', sa.Column('allow_negative_stock', sa.Boolean(), nullable=False, server_default=sa.true()))
    op.add_column('settings', sa.Column('default_low_stock_threshold', sa.Float(), nullable=False, server_default='5'))
    op.add_column('settings', sa.Column('default_payment_method', sa.String(length=10), nullable=False, server_default='cash'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'default_payment_method')
    op.drop_column('settings', 'default_low_stock_threshold')
    op.drop_column('settings', 'allow_negative_stock')
    op.drop_column('settings', 'enable_customer_selection')
    op.drop_column('settings', 'enable_barcode')
    op.drop_column('settings', 'auto_print_after_checkout')
    op.drop_column('settings', 'allow_discounts')
    op.drop_column('settings', 'default_tax_percent')
    op.drop_column('settings', 'date_format')
    op.drop_column('settings', 'decimal_precision')
    op.drop_column('settings', 'receipt_footer')
    op.drop_column('settings', 'starting_invoice_number')
    # ### end Alembic commands ###
