"""add held bills

Revision ID: e9782d44c912
Revises: 4ed26af3ad72
Create Date: 2026-07-23 10:18:41.404283

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e9782d44c912'
down_revision: Union[str, Sequence[str], None] = '4ed26af3ad72'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('held_bills',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=False),
    sa.Column('customer_name', sa.String(length=150), nullable=True),
    sa.Column('customer_phone', sa.String(length=50), nullable=True),
    sa.Column('discount_type', sa.String(length=10), nullable=True),
    sa.Column('discount_value', sa.Float(), nullable=False),
    sa.Column('tax_percentage', sa.Float(), nullable=False),
    sa.Column('payment_method', sa.String(length=10), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('lines', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_held_bills_created_at'), 'held_bills', ['created_at'], unique=False)
    op.create_index(op.f('ix_held_bills_tenant_id'), 'held_bills', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_held_bills_tenant_id'), table_name='held_bills')
    op.drop_index(op.f('ix_held_bills_created_at'), table_name='held_bills')
    op.drop_table('held_bills')
    # ### end Alembic commands ###
